- api-server/.eslintrc.js
- api-server/package.json
elsint가 prettier 규칙에 대한 정의를 찾지 못해서
생기는 오류에 대한 버그를 수정
> [Fix] prettier와 관련된 오류 수정

- api-server/api/graphql/index.js
- api-server/app.js
- api-server/package-lock.json
- api-server/package.json
- graphql 모듈 추가 및 관련 코드 추가
- helmet 모듈 추가 및 관련 코드 추가
- 환경에 따른 npm scripts 명령어 추가
> [Feat] graphql, helmet 설정 및 npm scripts 추가

- web/package-lock.json
- web/package.json
- web/src/containers/App/index.js
CSS를 관리하기 위하여 styled-component 설정.
자주 쓰는 색상들을 theme에 저장.
styled-component를 더 원활히 사용하기 위해 polished 패키지 설치.
> [Feat] styled-component 설정

- web/src/containers/App/index.js
- 필요 없는 더미 데이터 삭제
- components 디렉토리에 .gitkeep 파일을 추가
> [Fix] Web 디렉토리 구조 수정

- web/src/containers/App/index.js
색상이 'nnnnnn'으로 표기된 오타를 '#nnnnnn'으로 수정.
> [Fix] theme 내의 색상 오타 수정

- web/src/components/LikeIcon/SpanStyles.js
- web/src/components/LikeIcon/StyledSpan.js
- web/src/components/LikeIcon/Wrapper.js
- web/src/components/LikeIcon/index.js
- 게시물, 댓글의 '좋아요'기능을 위한 '좋아요'아이콘 구현.
- '좋아요'아이콘 클릭 시 제대로 눌렸는지 확인하기 위해 '좋아요'아이콘의 색상 변경 핸들러 구현.
> [Feat] 좋아요 아이콘 구현

- web/package-lock.json
- web/package.json
- web/src/containers/App/index.js
- web/src/containers/HomePage/index.js
- web/src/containers/UserPage/index.js
- web/src/index.js
> [Feat] React Router 추가

- web/src/components/Comment/Wrapper.js
- web/src/components/Comment/index.js
- web/src/components/CommentInput/Wrapper.js
- web/src/components/CommentInput/index.js
- web/src/components/CommentList/Wrapper.js
- web/src/components/CommentList/index.js
댓글 컴포넌트, 댓글 리스트 컴포넌트, 댓글 작성 컴포넌트 구현
> [Feat] 댓글 컴포넌트 구현

- web/src/components/LikeIcon/LikeIconSpan.js
좋아요 아이콘이 클릭 되었을 때와 클리 되지 않았을 때 위치가 다른
오류를 해결.
> [Fix] 좋아요 아이콘 위치 수정

- web/src/components/PostTop/MoreIcon.js
- web/src/components/PostTop/MoreModal.js
- web/src/components/PostTop/MoreModal/ModalBackground.js
- web/src/components/PostTop/MoreModal/ModalBlock.js
- web/src/components/PostTop/MoreModal/ModalContent.js
- web/src/components/PostTop/MoreModal/index.js
- web/src/components/PostTop/StyledLink.js
- web/src/components/PostTop/Wrapper.js
- web/src/components/PostTop/index.js
- web/src/components/ProfileIcon/Wrapper.js
- web/src/components/ProfileIcon/index.js
- web/src/containers/App/index.js
1. 게시물 상단 프로필 아이콘과 게시자 클릭시 개인 페이지로 이동하는 이벤트 추가
2. 모달 아이콘 클릭시 모달 등장
3. 모달 UI 구현
> [Feat] 게시물 상단 이벤트 추가

- api-server/.dockerignore
- api-server/Dockerfile
- api-server/Dockerfile-dev
- api-server/package-lock.json
- api-server/package.json
- compose-dev.yml
- compose-prod.yml
- web/.dockerignore
- web/Dockerfile
- web/Dockerfile-dev
- web/config/nginx/conf.d/default.conf
- 모든 운영체제에서 환경변수 설정 호환을 위한 cross-env 모듈 추가
- 배포 서버에 실행될 Nginx 설정 파일 추가
- production 용 Dockerfile 및 docker-compose 파일 추가
- development 용 Dockerfile 및 docker-compose 파일 추가
> [Feat] 서버 배포와 관련된 설정파일 추가

- web/src/components/CommentList/Wrapper.js
- web/src/components/PostContent/Wrapper.js
- web/src/components/PostContent/index.js
본문 및 댓글 내용을 렌더링하는 컴포넌트 구현.
CommentList 컴포넌트의 padding 값 제거.
close #66
> [Feat] 본문 및 댓글 렌더링 컴포넌트 구현

- web/package-lock.json
- web/package.json
- web/src/components/PostTop/MoreModal/ModalBackground.js
- web/src/components/PostTop/MoreModal/index.js
- web/src/components/PostTop/index.js
1. 모달 위치 수정.
2. 게시물로 이동 기능 추가.
3. 링크 복사하기 기능 추가.
4. 취소 버튼 혹은 배경클릭시 취소되는 기능 추가.
팔로우 취소 기능은 팔로우 취소 컴포넌트가 완료되면 추가 예정.
> [Feat] more modal에 관련된 기능 추가

- web/src/components/Comment/index.js
- web/src/components/PostContent/index.js
- web/src/components/PostText/Wrapper.js
- web/src/components/PostText/index.js
PostContent에서 본문 내용을 Comment 컴포넌트로 넘겨주던 것을
별도의 PostText 컴포넌트를 생성하여 사용.
> [Refactor] PostContent 의 본문 컴포넌트 수정

- web/src/components/Icon/IconImage.js
- web/src/components/Icon/IconSpan.js
- web/src/components/Icon/index.js
- web/src/components/LikeIcon/index.js
- icon-1.png 파일의 아이콘들에 대한 공통적인 처리를 위해 Icon 컴포넌트 구현.
- 구현한 Icon 컴포넌트를 이용해 LikeIcon 컴포넌트 리팩토링.
> [Refactor] LikeIcon을 응용해 아이콘에 대한 공통 모듈인 Icon 구현

- web/src/components/Icon/index.js
- web/src/containers/Navigation/Serach/Input.js
- web/src/containers/Navigation/Serach/SearchWrapper.js
- web/src/containers/Navigation/Serach/index.js
1. 검색창 UI 구현
2. 아이콘의 style 직접 수정할 수 있도록 props 수정
> 검색창 UI 구현하면서 아이콘 props 수정

- web/src/components/ProfileIcon/index.js
프로필 아이콘에서 이미지를 직접 할당할 수 있도록 수정.
> [Fix] 프로필 아이콘 이미지 동적 할당

- web/src/containers/App/index.js
- web/src/containers/Navigation/NavBackground.js
- web/src/containers/Navigation/Search/SearchWrapper.js
> [Fix] 네이게이션 마진 수정

- web/src/components/FollowButton/StyledFollowButton.js
- web/src/components/FollowButton/index.js
팔로잉 상태에따라 다른 형태를 가지는 팔로우버튼 구현
현재는 서버에 팔로우 상태를 조회할 수 없어 클릭 시 다른 상태를
보여주도록 구현. 추후 리팩토링할 예정
Close #26
> [Feat] 팔로우 버튼 구현

- web/src/components/Comment/Wrapper.js
- web/src/components/Comment/index.js
- web/src/components/CommentInput/Wrapper.js
- web/src/containers/PostDetailPage/PostDetailPageWrapper.js
- web/src/containers/PostDetailPage/PostSideBox/CommentList/index.js
- web/src/containers/PostDetailPage/PostSideBox/SideBoxWrapper.js
- web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/IconBox.js
- web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/IconList.js
- web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/IconWrapper.js
- web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/LikerCount.js
- web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/TimePassed.js
- web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/UtilityBlockWrapper.js
- web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/index.js
- web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/styles.js
- web/src/containers/PostDetailPage/PostSideBox/index.js
- web/src/containers/PostDetailPage/ViewPort.js
- web/src/containers/PostDetailPage/index.js
> [Feat] 상세 페이지 UI 구현

- web/src/components/Icon/IconImage.js
- web/src/components/LikeInfo/LikeCount.js
- web/src/components/LikeInfo/LikeInfoWrapper.js
- web/src/components/LikeInfo/LikerLink.js
- web/src/components/LikeInfo/LikerListModal/Header/ButtonWrapper.js
- web/src/components/LikeInfo/LikerListModal/Header/Cancel.js
- web/src/components/LikeInfo/LikerListModal/Header/HeaderWrapper.js
- web/src/components/LikeInfo/LikerListModal/Header/Title.js
- web/src/components/LikeInfo/LikerListModal/Header/index.js
- web/src/components/LikeInfo/LikerListModal/Header/styles.js
- web/src/components/LikeInfo/LikerListModal/Liker/FollowButton.js
- web/src/components/LikeInfo/LikerListModal/Liker/LikerInfo.js
- web/src/components/LikeInfo/LikerListModal/Liker/LikerInfoWrapper.js
- web/src/components/LikeInfo/LikerListModal/Liker/LikerWrapper.js
- web/src/components/LikeInfo/LikerListModal/Liker/index.js
- web/src/components/LikeInfo/LikerListModal/Liker/styles.js
- web/src/components/LikeInfo/LikerListModal/LikerList.js
- web/src/components/LikeInfo/LikerListModal/index.js
- web/src/components/LikeInfo/LikerListModal/styles.js
- web/src/components/LikeInfo/Profile.js
- web/src/components/LikeInfo/index.js
- web/src/components/LikeInfo/styles.js
- 좋아요 갯수에 대한 정보를 보여주는 LikeInfo 컴포넌트 구현
- 프로필 이미지, `좋아요 1개` 혹은 `외 xx명`을 눌렀을 시, 좋아요를 누른 사람들의 목록이 나오는 모달창 구현
close #13 
close #15 
close #16
> [Feat] 좋아요 갯수를 표시하는 LikeInfo 컴포넌트 구현

- web/src/components/CommentInput/index.js
- web/src/containers/HomePage/Post/PostBottom/AllCommentShowButton.js
- web/src/containers/HomePage/Post/PostBottom/Comment/CommentContent.js
- web/src/containers/HomePage/Post/PostBottom/Comment/CommentMoreButton.js
- web/src/containers/HomePage/Post/PostBottom/Comment/CommentWrapper.js
- web/src/containers/HomePage/Post/PostBottom/Comment/Commenter.js
- web/src/containers/HomePage/Post/PostBottom/Comment/index.js
- web/src/containers/HomePage/Post/PostBottom/Comment/styles.js
- web/src/containers/HomePage/Post/PostBottom/CommentIcon.js
- web/src/containers/HomePage/Post/PostBottom/CommentInputWrapper.js
- web/src/containers/HomePage/Post/PostBottom/CommentWrapper.js
- web/src/containers/HomePage/Post/PostBottom/IconGroup.js
- web/src/containers/HomePage/Post/PostBottom/IconWrapper.js
- web/src/containers/HomePage/Post/PostBottom/PostBottomWrapper.js
- web/src/containers/HomePage/Post/PostBottom/ShareIcon.js
- web/src/containers/HomePage/Post/PostBottom/UpdatedTime.js
- web/src/containers/HomePage/Post/PostBottom/index.js
- web/src/containers/HomePage/Post/PostBottom/styles.js
- web/src/containers/HomePage/Post/PostImage.js
- web/src/containers/HomePage/Post/PostWrapper.js
- web/src/containers/HomePage/Post/index.js
- web/src/containers/HomePage/Post/styles.js
- web/src/containers/HomePage/PostList/PostListWrapper.js
- web/src/containers/HomePage/PostList/index.js
- web/src/containers/HomePage/index.js
- Main Page의 타임라인 게시물 레이아웃 구현
- 좋아요 컴포넌트 배치
- more 모달 배치
close #118
close #120 
close #121
close #122
> [Feat] 게시물 레이아웃 구현

- README.md
> [Docs] Readme 수정

- api-server/bin/server.js
- api-server/db/migrations/20191117094148-create-user.js
- api-server/db/migrations/20191117104241-create-post.js
- api-server/db/migrations/20191117124029-associate-user-post.js
- api-server/db/migrations/20191117125445-associate-user-post.js
- api-server/db/migrations/20191117131058-associate-user-post.js
- api-server/db/migrations/20191117131642-create-hash-tag.js
- api-server/db/migrations/20191117132239-associate-user-hashtag.js
- api-server/db/migrations/20191117132947-associate-post-hashtag.js
- api-server/db/migrations/20191117140021-create-reply.js
- api-server/db/migrations/20191117143438-associate-user-reply.js
- api-server/db/migrations/20191118062418-create-user-follow.js
- api-server/db/seeders/20191120020931-user.js
- api-server/db/seeders/20191121020931-post.js
- api-server/db/seeders/20191122020931-replies.js
- api-server/db/seeders/20191123020931-hashTag.js
eslint 문법에 저촉되는 파일들 수정
포트를 3000에서 4000으로 변경
seeder에서 테이블 명 카멜케이스로 변경
> [Refact] 파일 정리

- web/src/containers/App/AppWrapper.js
- web/src/containers/App/index.js
- web/src/containers/Navigation/NavBackground.js
position를 fixed로 변경.
배경 색을 white로 변경.
태그를 nav 로 수정.
> [Refact] 네이게이션 position 수정

- web/src/components/FollowButton/index.js
- web/src/components/FollowCheckingModal/ModalHeaderText.js
- web/src/components/FollowCheckingModal/index.js
- web/src/components/FollowCheckingModal/styles.js
팔로우 취소 또는 요청됨 취소 시 취소를 확인하는 모달 구현.
z-index를 부여하기위해 Modal 컴포넌트 하위의 ModalBackground와
ModalWrapper 컴포넌트들을 재활용. 프로필 사진과 확인 문구의
데이터 반영은 추후 fetch요청 구현 시 함께 구현 예정.
Close #27
> [Feat] FollowCheckingModal 구현

- web/src/components/ToolTip/ToolTipBody.js
- web/src/containers/Navigation/Search/index.js
- clear 버튼 누르면 검색결과 툴팁이 사라져야 한다.
- input에 \ 가 들어올 경우에 대한 예외처리를 해야 한다.
- 검색 툴팁창을 height를 주고 overflow에 대해 scroll 처리를 해야 한다.
위 버그 수정했습니다.
> [Refact] 검색에 대한 버그 수정

- web/src/containers/App/index.js
- web/src/containers/PostDetailPage/index.js
> [Fix] URL에 따라 상세 페이지로 라우팅

- api-server/api/graphql/index.js
- api-server/api/graphql/mutations/CommentMutation.js
- api-server/api/graphql/queries/CommentQuery.js
- api-server/api/graphql/queries/PostDetailQuery.js
- api-server/api/graphql/queries/SearchHashtagQuery.js
- api-server/api/graphql/queries/SearchUserQuery.js
- api-server/api/graphql/queries/index.js
- api-server/api/graphql/types/index.js
graphql 하위 디렉토리에 index.js 파일들을 추가.
> [Refact] API 구조 변경

- api-server/api/graphql/index.js
- api-server/api/graphql/mutations/CommentMutation.js
- api-server/api/graphql/mutations/index.js
- api-server/api/models/comment.js
- web/package-lock.json
- web/package.json
- web/src/components/CommentInput/index.js
- web/src/components/CommentInput/reducer.js
- web/src/containers/HomePage/Post/index.js
- web/src/containers/PostDetailPage/PostSideBox/CommentList/index.js
- web/src/containers/PostDetailPage/PostSideBox/context.js
- web/src/containers/PostDetailPage/PostSideBox/index.js
- web/src/containers/PostDetailPage/PostSideBox/reducer.js
- web/src/useFetch.js
- web/src/useMutation.js
댓글 달기 기능 구현
- 댓글 입력 시 mutation fetch 전송
- 성공적으로 입력시 state 업데이트
> [Feat] 댓글 달기

- web/src/containers/Navigation/index.js
> [Fix] test data 수정

- web/src/components/CommentInput/index.js
- web/src/components/ProfileIcon/index.js
- web/src/containers/PostDetailPage/PostSideBox/reducer.js
- web/src/hooks/useFetch.js
- 상세 페이지에서 댓글 작성 요청 부분 수정
- 기본 프로필 이미지 설정
> [Fix] detail page

- web/src/components/CommentInput/index.js
- web/src/containers/App/index.js
- web/src/containers/HomePage/index.js
- web/src/containers/Navigation/index.js
- web/src/containers/PostDetailPage/PostSideBox/index.js
> [Fix] 더미 유저 설정

- api-server/db/seeders/20191120020931-user.js
- api-server/db/seeders/20191121020931-post.js
- api-server/db/seeders/20191124110517-userFollows.js
- api-server/db/seeders/20191125063643-log.js
> [Fix] 데모용 시더파일 수정

- api-server/db/seeders/20191122020931-comments.js
- web/src/containers/PostDetailPage/index.js
게시물 상세 페이지의 이미지 URL을 로컬 값에서 외부 경로로 변경.
> [Fix] 상세 페이지 게시물 imgaeURL 변경

- web/src/components/CommentInput/index.js
- web/src/containers/HomePage/Post/PostBottom/index.js
- web/src/containers/HomePage/Post/index.js
- web/src/containers/HomePage/index.js
- web/src/containers/HomePage/reducer.js
메인 페이지에 있는 게시글에서 바로 댓글을 달 수 있는 기능 추가.
> [Feat] 메인 페이지 게시글 댓글 달기 기능

- web/src/components/ToolTip/index.js
- web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmToolTipWrapper.js
- web/src/containers/Navigation/Alarm/AlarmToolTip/index.js
- web/src/containers/Navigation/Alarm/index.js
- web/src/containers/Navigation/Search/SearchToolTip/SearchToolTipWrapper.js
알림과 검색 결과 툴팁 위치 변경. 알림 데이터가 없을 때 버그가
발생하는 부분 수정.
> [Fix] 툴팁 위치 변경및 알림결과 버그 수정

- web/.env
- web/src/components/PostTop/MoreModal/index.js
- web/src/containers/Navigation/Search/index.js
- web/src/containers/NewPostPage/index.js
- web/src/hooks/useFetch.js
- web/src/useFetch.js
> [Refact] 하드 코딩된 URL 제거

- api-server/app.js
- api-server/upload.js
- web/src/containers/App/index.js
- web/src/containers/Navigation/index.js
db에 object storage의 전체 주소 저장하도록 수정.
upload파일 환경변수 사용할 때 오류 있어 수정.
newpost url이 username의 url과 겹쳐 수정. -> /new/post로
> [Fix] 새게시물 관련 오류 수정

- api-server/api/graphql/queries/FollowingPostListQuery.js
- api-server/api/services/PostService.js
- web/src/containers/HomePage/Post/index.js
- web/src/containers/HomePage/index.js
- web/src/containers/HomePage/queries/followingPostList.js
- web/src/containers/HomePage/reducer.js
- web/src/utils/index.js
- web 프로젝트에 dotenv 의존 모듈 추가 및 설정
- 메인페이지 게시물의 무한 스크롤링 기능 구현
> [Feat] 메인페이지 무한 스크롤링 기능 구현

- oauth-server/.gitignore
- oauth-server/app.js
- oauth-server/bin/www
- oauth-server/package-lock.json
- oauth-server/package.json
- oauth-server/routes/index.js
- oauth-server/views/error.jade
- oauth-server/views/index.jade
- oauth-server/views/layout.jade
- express generator를 이용해 oauth-server 디렉토리 구조 생성.
> [Feat] oauth-server 디렉토리 구조 생성

- web/package-lock.json
- web/package.json
- web/src/index.js
> [Refact] apollo 세팅

- oauth-server/.gitignore
- oauth-server/.sequelizerc
- oauth-server/config/sequelize-config.js
- oauth-server/db/index.js
- oauth-server/db/migrations/20191203063359-create-client.js
- oauth-server/models/client.js
- oauth-server/package-lock.json
- oauth-server/package.json
client table만들기 위해 authorization server에 sequelize 설정.
> [Feat] authorization server의 sequelize 설정

- api-server/app.js
- compose-dev.yml
- compose-prod.yml
- web/config/nginx/conf.d/default.conf
- api-server port 변경에 따른 docker 설정 변경
- nginx의 reverse proxy 설정 추가
> [Fix] docker 및 nginx 설정 변경

- oauth-server/oauth/src/validator/index.js
- oauth-server/oauth/test/validator/validator.test.js
- oauth-server/package-lock.json
- oauth-server/package.json
- request의 parameter들이 RFC 6749에 명시된 형태인지 검증하기 위한 Validator 구현.
> [Feat] Validator 클래스 구현

- oauth-server/oauth/src/error-types/access-denied-error.js
- oauth-server/oauth/src/error-types/index.js
- oauth-server/oauth/src/error-types/invalid-client-error.js
- oauth-server/oauth/src/error-types/invalid-grant-error.js
- oauth-server/oauth/src/error-types/invalid-request-error.js
- oauth-server/oauth/src/error-types/invalid-scope-error.js
- oauth-server/oauth/src/error-types/server-error.js
- oauth-server/oauth/src/error-types/temporarily-unavailable-error.js
- oauth-server/oauth/src/error-types/unauthorized-client-error.js
- oauth-server/oauth/src/error-types/unsupported-grant-type-error.js
- oauth-server/oauth/src/error-types/unsupported-response-type-error.js
- oauth-server/oauth/test/error-types/error-types.test.js
- oauth-server/package.json
- RFC 6749문서에 나와있는 Error Response Type마다 Error 클래스 구현 및 테스트 코드 구현.
> [Feat] OAuth 2.0의 Error Response에 대한 Error 클래스 구현

- api-server/db/seeders/20191121020931-post.js
- api-server/db/seeders/20191124110517-userFollows.js
유저 101명 게시글 1000개
1번 유저가 100명을 팔로우
> [fix] 더미 데이터 수정

- oauth-server/oauth/src/utils/index.js
- oauth-server/oauth/test/utils/utils.test.js
- oauth-server/oauth/test/validator/validator.test.js
- oauth-server/package-lock.json
- oauth-server/package.json
- oauth-server/services/registration.js
- oauth-server/test/services/registration.test.js
> [Feat] Access Token & Refresh Token 생성기 구현

- web/src/containers/NewPostPage/NewPostWrapper.js
- web/src/containers/NewPostPage/index.js
form과 fetch가 이중으로 제출되어 일어나는 오류 수정을 위해
form을 제거하고 router를 통해 redirection 되도록 수정.
> [Fix] 새게시물 페이지 오류 수정

- api-server/api/graphql/index.js
- api-server/api/graphql/queries/SearchQuery.js
- api-server/api/graphql/queries/index.js
- api-server/api/graphql/types/SearchType.js
- api-server/api/graphql/types/index.js
- web/src/containers/Navigation/Search/SearchToolTip/SearchResult/index.js
- web/src/containers/Navigation/Search/SearchToolTip/SearchResultList.js
- web/src/containers/Navigation/Search/index.js
- web/src/containers/Navigation/queries/index.js
1. 검색 결과를 랜덤이 아닌 더 정확도가 높은 것을 기준으로 정렬하도록 개선.
2. 매 글자마다 fetch를 보내지않고 1초의 입력 지연이 있을시 보내도록 디바운싱 적용.
> [Impv] 검색 기능 성능 개선

- web/public/index.html
- web/public/manifest.json
> [Fix] html, manifest.json 파일 수정

- web/src/containers/Navigation/index.js
> [Add] 로고 클릭시 최상단으로 이동

- web/src/containers/HomePage/index.js
다른 페이지로 이동한 후 메인페이지로 돌아왔을 때 스크롤 안되는 문제
해결
close #256
> [Fix] 스크롤 이슈 해결

- api-server/api/middlewares/Authenticator.js
- api-server/api/models/User.js
- api-server/api/routes/AccountRoute.js
- api-server/api/services/UserService.js
- api-server/app.js
- api-server/db/migrations/20191117094148-create-user.js
- api-server/package-lock.json
- api-server/package.json
- api-server/test/api/AccountRoute.test.js
- api-server/test/services/PostService.test.js
- api-server/test/services/UserService.test.js
- api-server/utils/bcrypt.js
- 회원가입 기능 구현
- passport 모듈을 이용해 로그인 기능 구현
> [Feat] 회원가입 및 로그인 기능 구현

- api-server/api/graphql/index.js
- api-server/api/graphql/mutations/PostMutation.js
- api-server/api/graphql/mutations/index.js
- api-server/db/migrations/20191117124029-associate-user-post.js
- api-server/db/migrations/20191117125445-associate-user-post.js
- api-server/db/migrations/20191117131058-associate-user-post.js
- api-server/db/migrations/20191117132239-associate-user-hashtag.js
- api-server/db/migrations/20191117132947-associate-post-hashtag.js
- api-server/db/migrations/20191117140021-create-comment.js
- api-server/db/migrations/20191117143438-associate-user-comment.js
- api-server/db/migrations/20191125043301-create-log.js
- web/src/components/PostTop/MoreModal/index.js
- web/src/components/PostTop/MoreModal/queries/deletePost.js
- web/src/components/PostTop/MoreModal/queries/index.js
> [Feat] 게시글 삭제 기능

- web/src/containers/HomePage/index.js
게시글 작성 후 메인 페이지에서 작성한 게시글이 나오지 않는 버그 수정
무한 스크롤이 의도하지 않은 곳에서 데이터를 요청하는 버그 수정
> [Fix] 메인 페이지 버그 수정

- api-server/api/graphql/index.js
- api-server/api/graphql/mutations/PostMutation.js
- api-server/api/graphql/mutations/index.js
- api-server/app.js
- web/src/containers/App/index.js
- web/src/containers/EditPostPage/EditBox/ButtonGroup.js
- web/src/containers/EditPostPage/EditBox/EditBoxWrapper.js
- web/src/containers/EditPostPage/EditBox/StyledButton.js
- web/src/containers/EditPostPage/EditBox/StyledTextBox.js
- web/src/containers/EditPostPage/EditBox/index.js
- web/src/containers/EditPostPage/EditBox/styles.js
- web/src/containers/EditPostPage/PostDetailPageWrapper.js
- web/src/containers/EditPostPage/ViewPort.js
- web/src/containers/EditPostPage/index.js
- web/src/containers/EditPostPage/queries/getPost.js
- web/src/containers/EditPostPage/queries/index.js
- web/src/containers/EditPostPage/queries/updatePost.js
- web/src/containers/EditPostPage/styles.js
> [Feat] edit post page

- api-server/api/graphql/queries/UserPageQuery.js
- api-server/api/graphql/types/UserInfoType.js
- api-server/api/graphql/types/UserPageType.js
- api-server/api/services/UserPageService.js
- web/src/containers/App/index.js
- web/src/containers/UserPage/UserPageInfo/UserInfo/CountIndicator/index.js
- web/src/containers/UserPage/UserPageInfo/UserInfo/index.js
- web/src/containers/UserPage/UserPageInfo/index.js
- web/src/containers/UserPage/index.js
UserPage에서 UserInfo가 출력되도록 구현. 추가적으로 함께 리팩토링 실시.
> [Feat] UserPage의 UserInfo 구현

- web/src/components/Loading/Backdrop.js
- web/src/components/Loading/SpinnerWrapper.js
- web/src/components/Loading/index.js
- web/src/components/Loading/styles.js
- web/src/components/Spinner/Spinner.js
- web/src/components/Spinner/SpinnerWrapper.js
- web/src/components/Spinner/index.js
- web/src/components/Spinner/styles.js
- web/src/containers/HomePage/Post/CommentInput/CommentInputWrapper.js
- web/src/containers/HomePage/Post/CommentInput/index.js
- web/src/containers/HomePage/SpinnerWrapper.js
- web/src/containers/HomePage/index.js
- web/src/containers/HomePage/styles.js
- web/src/containers/NewPostPage/NewPostWrapper.js
- web/src/containers/NewPostPage/index.js
- web/src/containers/PostDetailPage/PostSideBox/CommentInput/CommentInputWrapper.js
- web/src/containers/PostDetailPage/PostSideBox/CommentInput/index.js
- Spinner 컴포넌트
-  Loading컴포넌트 구현 (backdrop과 Spinner를 포함)
- 메인 페이지 포스트
- 댓글 입력시
- 새 게시글 작성시
> [Feat] spinner 컴포넌트 구현

- api-server/api/graphql/index.js
- api-server/api/graphql/mutations/RequestFollowing.js
- api-server/api/graphql/mutations/RequestFollowingCancellation.js
- api-server/api/graphql/mutations/index.js
- api-server/api/graphql/types/UserFollower.js
- api-server/api/graphql/types/UserInfoType.js
- api-server/api/graphql/types/index.js
- api-server/app.js
- web/src/components/FollowButton/StyledFollowButton.js
- web/src/components/FollowButton/index.js
- web/src/components/FollowCheckingModal/index.js
- web/src/containers/UserPage/UserPageInfo/UserInfo/StyledFollowButton.js
- web/src/containers/UserPage/UserPageInfo/UserInfo/index.js
- web/src/containers/UserPage/UserPageInfo/index.js
- web/src/containers/UserPage/index.js
- FollowButton 팔로우 요청과 팔로우 취소요청 구현.
- FollowButton 정상 작동을 위해 필요 props 전달 요망.
- UserPage에서 FollowButton을 정상 작동하기 위해 props 전달.
> [Feat] FollowButton 팔로우 요청, 팔로우 취소 요청 구현

- api-server/db/migrations/20191117104241-create-post.js
- api-server/db/migrations/20191117125445-associate-user-post.js
- web/src/containers/HomePage/Post/CommentInput/index.js
- web/src/containers/NewPostPage/index.js
- web/src/containers/PostDetailPage/PostSideBox/CommentInput/index.js
> [Refact] 일부 수정

- web/src/components/PostTop/MoreModal/index.js
- web/src/containers/PostDetailPage/PostSideBox/index.js
게시글 수정 클릭시 페이지 이동 하지 않는 버그 수정
게시글 삭제시 페이지 이동하지 않는 버그 수정
> [fix] UD 기능 수정

- web/package-lock.json
- web/package.json
- web/src/containers/App/index.js
- web/src/containers/DeveloperPage/Registration/Button.js
- web/src/containers/DeveloperPage/Registration/Input.js
- web/src/containers/DeveloperPage/Registration/P.js
- web/src/containers/DeveloperPage/Registration/RegistrationWrapper.js
- web/src/containers/DeveloperPage/Registration/Select.js
- web/src/containers/DeveloperPage/Registration/Span.js
- web/src/containers/DeveloperPage/Registration/Title.js
- web/src/containers/DeveloperPage/Registration/index.js
- web/src/containers/DeveloperPage/Registration/styles.js
- web/src/containers/DeveloperPage/index.js
새로운 client app을 등록하기 위한 페이지 구현
> [Feat] client registration page

- oauth-server/app.js
- oauth-server/package-lock.json
- oauth-server/package.json
- oauth-server/routes/index.js
cors문제와 변수 선언 scope의 문제로 client의 값이 제대로 받아지지
않아서 cors library 설치하고 변수 선언 수정.
> [Fix] client의 값이 제대로 받아지지 않는 오류 수정

- web/src/containers/HomePage/Post/PostMiddle/PostImage.js
- web/src/containers/HomePage/Post/PostMiddle/index.js
- 게시물 이미지 더블클릭 시 좋아요가 해제될 때 web 프로젝트가 터지는 버그 수정
> [Fix] 게시물 이미지 더블클릭 이벤트 버그 수정

- web/src/containers/ErrorPage/ErrorImage.js
- web/src/containers/ErrorPage/ErrorWrapper.js
- web/src/containers/ErrorPage/index.js
- web/src/containers/ErrorPage/styles.js
- web/src/containers/PostDetailPage/index.js
404 또는 500에러에 대한 에러 페이지 구현.
현재 없는 post 페이지 url로 들어가면 404에러 페이지 테스트 가능. 
차후 기능들의 에러 처리가 끝나면 적용 예정.
> [Feat] 에러 페이지 구현

- api-server/api/graphql/index.js
- api-server/api/graphql/queries/hashTagPageQuery.js
- api-server/api/graphql/queries/index.js
- api-server/api/graphql/types/HashTagPageType.js
- api-server/api/graphql/types/index.js
- web/src/containers/App/index.js
- web/src/containers/HashTagPage/HashTagInfoDetailWrapper.js
- web/src/containers/HashTagPage/HashTagInfoWrapper.js
- web/src/containers/HashTagPage/HashTagPageWrapper.js
- web/src/containers/HashTagPage/PostCardListWrapper.js
- web/src/containers/HashTagPage/index.js
- web/src/containers/HashTagPage/styles.js
HashTagpage 구현. 존재하지않는 HashTag입력 시 예외처리 완료.
> [Feat] HashTagPage구현

- web/src/components/PostTop/PostTopWrapper.js
- web/src/containers/HomePage/Post/PostMiddle/PostImage.js
- web/src/containers/HomePage/Post/PostWrapper.js
- web/src/containers/PostDetailPage/PostDetailPageWrapper.js
- web/src/index.js
UI개선을 위해 천제 페이지의 배경색을 하얀색에서 다른색으로 변경.
> [Refact] 전체 페이지 배경색 변경

- api-server/api/graphql/mutations/RequestFollowing.js
RequestFollowing.js 파일에서 디버깅시 사용했던 불필요한 console.log제거
> [Refact] RequestFollowing.js 불필요 console.log 제거

- api-server/api/graphql/mutations/UserMutation.js
- api-server/api/graphql/types/index.js
index.js에 PostType이 두번 있던 것을 수정
Usermuation에 잘못된 값이 들어있던 것을 수정
> [Fix] 오타 수정

- web/src/components/ToolTip/ToolTipArrow.js
- web/src/components/ToolTip/ToolTipBody.js
- web/src/components/ToolTip/ToolTipWrapper.js
- web/src/containers/Navigation/Search/Input.js
- web/src/containers/Navigation/Search/SearchToolTip/SearchResult/index.js
- web/src/containers/Navigation/Search/SearchToolTip/SearchResultList.js
- web/src/containers/Navigation/Search/SearchToolTip/SearchToolTipWrapper.js
- web/src/containers/Navigation/Search/SearchToolTip/index.js
- web/src/containers/Navigation/Search/index.js
1. 검색툴팁 UI에서 어색한 부분 UI 수정
2. 검색 툴팁에서 결과페이지로 이동하도록 링크 추가
> [Fix] 검색 툴팁 UI 변경, 링크 추가

- api-server/api/graphql/types/PostType.js
- web/src/containers/PostDetailPage/index.js
쿼리가 변경되어 상세 페이지에 접근이 되지 않는 버그가 발생하여 이를
수정.
> [Fix] 상세 페이지가 뜨지 않는 버그 수정

- web/src/components/Loading/Backdrop.js
- web/src/components/Loading/SpinnerWrapper.js
- web/src/components/Loading/index.js
- web/src/components/Loading/styles.js
- web/src/containers/HomePage/Post/CommentInput/CommentInputWrapper.js
- web/src/containers/HomePage/Post/CommentInput/StyledButton.js
- web/src/containers/PostDetailPage/PostSideBox/CommentInput/CommentInputWrapper.js
- web/src/containers/PostDetailPage/PostSideBox/CommentInput/StyledButton.js
스피너의 위치가 positon absolute로 조정 시  오른쪽 하단에 위치해서
flex를 사용해서 가운데에 위치하도록 수정.
> [Fix] 스피너 위치를 상위 컴포넌트의 가운데에 오도록 수정

- web/.eslintrc.js
- web/src/components/Icon/IconImageSelector.js
- web/src/components/Icon/index.js
- web/src/components/LikeIcon/index.js
- web/src/containers/HomePage/Post/PostMiddle/CommentIcon.js
- web/src/containers/HomePage/Post/PostMiddle/index.js
- web/src/containers/Navigation/Alarm/index.js
- web/src/containers/Navigation/index.js
> [Refact] 아이콘 리팩토링

- api-server/api/graphql/queries/LogQuery.js
- api-server/api/graphql/types/AlarmFromUserType.js
- api-server/api/graphql/types/LogType.js
- api-server/api/models/User.js
- api-server/api/models/UserFollow.js
- api-server/api/services/LogService.js
- web/src/components/ToolTip/ToolTipWrapper.js
- web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmResult/AlarmFollowButtn.js
- web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmResult/index.js
- web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmResult/styles.js
- web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmToolTipWrapper.js
- web/src/containers/Navigation/Alarm/AlarmToolTip/index.js
- web/src/containers/Navigation/queries/index.js
1. 알람 툴팁 UI 변경
2. 팔로우 상태일 경우 팔로우 버튼 삽입
3. 게시물 클릭시 게시물로 이동
> [Fix] 알람 툴팁 관련 버그 수정

- web/src/containers/HomePage/index.js
- 더 이상 게시글이 없을 경우 fetch 중단
- 스크롤 중간에서 fetch 되도록 추가
> [Refact] 홈페이지 스크롤 개선

- api-server/api/services/PostService.js
- api-server/app.js
- api-server/package-lock.json
- api-server/package.json
기존 postURL은 이미지 리소스의 etag로 구분되어 겹치는 경우가 발생해서
겹치지 않도록 하기 위해 short-uuid로 생성하도록 변경.
closed #309
> [Fix] postURL 유니크하게 생성되도록 수정

- web/src/components/FollowButton/StyledFollowButton.js
- web/src/components/FollowButton/index.js
followStatus 옵션값의 변경에따라 기능과 UI 변경. 자세한 설명은 커밋 본문과 issue #307 을 참고바람.
Close #307
> [팔로우버튼] followStatus에 따른 FollowButton 기능변화 리팩토링

- api-server/api/graphql/queries/UserPageQuery.js
- api-server/api/graphql/types/UserInfoType.js
- api-server/api/services/UserPageService.js
- web/src/containers/UserPage/UserPageInfo/index.js
- web/src/containers/UserPage/index.js
- UserPage에서 요청을 보낼 때 유저페이지의 해당 유저 이름을 writer라는 이름으로 매개변수를 전달하고 있었음. 하지만 글쓰는것과 관계가 없어 부적절한 변수명이라 판단되어 username으로 이름 변경.
- UserPage에서 프로필 이미지가 반영이되지 않던 것을 반영되도록 수정
Close #297
> [유저페이지] 유저페이지 변수명 수정 및 프로필사진 반영

- web/src/containers/App/UserContext.js
- web/src/containers/App/index.js
- web/src/containers/HomePage/Post/CommentInput/index.js
- web/src/containers/HomePage/index.js
- web/src/containers/NewPostPage/index.js
- web/src/containers/PostDetailPage/PostSideBox/CommentInput/index.js
- web/src/containers/PostDetailPage/PostSideBox/index.js
사용자 정보 데이터가 더미 데이터로 되어 있던 것들을 전부 실제 데이터로
변경함.
> [Fix] 더미 데이터를 실제 데이터로 변경

- api-server/api/middlewares/auth.js
second단위로 착각하여 maxAge 값을 millisecond 단위로 수정.
> [Fix] cookie의 maxAge 값 수정

- web/src/containers/HomePage/Post/PostText/MainText/index.js
- web/src/containers/HomePage/Post/PostText/MainText/lib/index.js
- 게시글 본문에 해시태그나 사람태그가 있을 경우, 이를 눌렀을 때 특정 URL로 리다이렉션되도록 해당부분을 Link로 교체하는 기능 구현.
close #272
> [Feat] 해시/사람 태그 구현

- api-server/api/graphql/queries/FollowingPostListQuery.js
- api-server/api/graphql/queries/PostDetailQuery.js
- api-server/api/graphql/types/PostType.js
- web/src/containers/PostDetailPage/index.js
- web/src/containers/PostDetailPage/queries/index.js
게시글의 좋아요가 게시글 작성자와 연동 되던 버그를 수정.
> [Fix] 게시글 좋아요 버그 수정

- web/src/components/ProfileIcon/index.js
프로필 아이콘 값이 null일 경우 기본 값으로 설정됨.
> [Fix] 프로필 사진 기본값 수정

- web/src/containers/NewPostPage/index.js
본문의 값이 formData에 잘못 넣어져서 값이 저장되지 않아 제대로 들어
가도록 수정.
> [Fix] 새게시물 본문 입력 버그 수정

- web/src/components/Button/index.js
버튼의 테두리에 button의 기본 테두리가 설정 되어 있던 것을 제거.
> [Fix] 버튼의 테두리 수정

- api-server/app.js
- 브라우저 재 접속시 기존에 있던 session을 보내지 않던 버그 수정.
> [Fix] session 버그 수정

- web/src/containers/AccountPage/lib/encryptor.js
- web/src/containers/AccountPage/lib/handlers.js
- web/src/containers/AccountPage/lib/validator.js
- web/src/index.js
- web/src/utils/index.js
- 로그인/회원가입 폼 제출 시 password input의 내용이 길어지는 현상 제거.
> [Fix] password Input 버그 수정

- web/src/components/Icon/index.js
- web/src/containers/UserPage/UserPageInfo/UserInfo/Logout/LogoutWrapper.js
- web/src/containers/UserPage/UserPageInfo/UserInfo/Logout/index.js
- web/src/containers/UserPage/UserPageInfo/UserInfo/index.js
> [feat] 로그아웃 아이콘 제작

- api-server/api/routes/account-route.js
- web/src/containers/UserPage/UserPageInfo/UserInfo/Logout/index.js
> [Feat] 로그아웃 기능 구현

- web/src/containers/UserPage/UserPageInfo/UserInfo/Logout/index.js
- 로그아웃 이벤트 이후 메인페이지로 리다이렉션 되도록 구현.
> [Fix] 로그아웃 버그 수정

- web/src/containers/App/index.js
- web/src/containers/HomePage/Post/CommentInput/index.js
- web/src/containers/HomePage/index.js
- web/src/containers/NewPostPage/index.js
- web/src/containers/PostDetailPage/PostSideBox/CommentInput/index.js
- web/src/containers/PostDetailPage/PostSideBox/index.js
- web/src/containers/PostDetailPage/index.js
- web/src/containers/UserPage/UserPageInfo/UserInfo/Logout/index.js
- 로그아웃 시 초기화면인 로그인 폼 페이지가 뜨지 않고 메인게시물 페이지가 렌더링되어서 이에 대한 버그 수정.
> [Fix] 로그아웃 시 초기화면이 보이지 않는 버그 수정

- api-server/api/graphql/input-types/PostLikeInputType.js
- api-server/api/graphql/mutations/PostLikeMutation.js
- api-server/api/services/PostService.js
- web/src/containers/HomePage/Post/PostMiddle/index.js
- web/src/containers/HomePage/queries/followingPostList.js
- web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/index.js
- web/src/containers/PostDetailPage/queries/index.js
- web/src/queries/createPostLike.js
포스트를 좋아요 할 때 상대방에게 알림이 가게 하기 위해서
좋아요를 누를 때 로그 테이블에 insert하는 기능 추가.
> [Feat] 포스트 좋아요 할 때 로그 테이블에 insert

- api-server/api/middlewares/auth.js
- api-server/api/routes/account-route.js
- api-server/api/services/UserService.js
> [Fix] myInfo 쿠키 세팅 변경

- web/config/nginx/conf.d/default.conf
- /account endpoint에 대한 reverse proxy 설정 추가.
> [Fix] nginx 설정 변경

- web/src/containers/App/AccountRoute.js
- web/src/containers/App/AuthRoute.js
- web/src/containers/App/index.js
- web/src/containers/UserPage/UserPageInfo/UserInfo/Logout/index.js
- 브라우저 재 접속 시 메인페이지에서 유저프로필 클릭 시 다시 메인페이지로 리다이렉트되는 버그 수정.
> [Fix] 유저프로필 클릭 시 리다이렉트되는 버그 수정

- api-server/api/routes/account-route.js
- 배포서버에서 /account/signin, /account/signup URL 새로고침 시 404 NOT Found가 뜨는 버그 수정.
close #369
> [Fix] 새로고침 버그 수정

- web/src/containers/HomePage/index.js
1. 요청이 중복 되어서 보내지는 버그 해결
2. 새 게시글 작성 시 두 번 렌더링 되는 버그 해결
close #357 #353 #344
> [Fix] 메인 페이지 버그 해결

- web/src/containers/PostDetailPage/PostSideBox/CommentInput/index.js
- web/src/containers/PostDetailPage/PostSideBox/PostContent/CommentList/Comment/Content/ContentWrapper.js
- web/src/containers/PostDetailPage/PostSideBox/PostContent/CommentList/Comment/Content/Username.js
- web/src/containers/PostDetailPage/PostSideBox/PostContent/CommentList/Comment/Content/index.js
- web/src/containers/PostDetailPage/PostSideBox/PostContent/PostText/Content/index.js
- web/src/containers/PostDetailPage/PostSideBox/PostContent/index.js
- web/src/containers/PostDetailPage/PostSideBox/index.js
1. 댓글 작성시 가로 스크롤 안생기도록 수정
2. 댓글 입력시 최상단으로 이동
> [Refact] 댓글 관련 기능 리택토링

- api-server/api/graphql/mutations/CommentMutation.js
- api-server/api/graphql/types/UserType.js
- web/src/containers/HomePage/Post/CommentInput/index.js
- web/src/containers/HomePage/Post/PostMiddle/index.js
- web/src/containers/HomePage/Post/index.js
- web/src/containers/PostDetailPage/PostSideBox/CommentInput/index.js
- web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/index.js
- web/src/containers/PostDetailPage/PostSideBox/index.js
- web/src/queries/createComment.js
- web/src/queries/followingPostList.js
- web/src/queries/readPost.js
댓글을 남길시 포스트작성자의 알림에 뜨도록 로그 table에 추가하도록 수정.
> [Feat] 댓글 남길시 로그에 남도록 추가

- api-server/api/graphql/queries/LogQuery.js
- web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmResult/index.js
- web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmResultList.js
- web/src/containers/Navigation/Alarm/AlarmToolTip/index.js
- web/src/queries/getLogs.js
1. 알람 로그 최신순으로 출력하도록 수정
2. 알람 로그에서 link 이동시 툴팁 닫히도록 수정
> [Fix] 알람 관련 버그 수정

- api-server/api/graphql/mutations/PostLikeMutation.js
- api-server/api/graphql/types/UserType.js
- web/src/components/LikeInfo/index.js
- web/src/containers/HomePage/Post/PostMiddle/index.js
- web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/index.js
- web/src/queries/createPostLike.js
- web/src/queries/deletePostLike.js
- web/src/utils/LikeHandler.js
1. 좋아요를 누르고 잠시 후 취소하면 요청이 보내어지지 않는 버그 해결
2. 메인 페이지 및 상세 페이지의 좋아요 연동 및 속도 개선
> [Fix] 좋아요 버그 처리 및 성능 향상

- web/src/containers/HomePage/NoFollowing/index.js
- web/src/containers/HomePage/index.js
- web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/index.js
- 더 이상 새로운 게시글이 없을 경우 toast로 알림이 나오도록 변경
- 팔로우 하는 사람들의 게시글이 하나도 없을 경우 처리
> [Refact] 메인 페이지 개선

- api-server/api/graphql/mutations/PostMutation.js
- api-server/app.js
- web/src/containers/App/index.js
- web/src/containers/EditPostPage/EditBox/index.js
- web/src/containers/EditPostPage/index.js
- web/src/queries/readPost.js
- web/src/queries/updatePost.js
1. 게시글 수정 페이지 최초 접근 시 에러 발생
2. 게시글 수정이 바로 반영되지 않음
3. 권한이 없는 사용자가 수정 페이지에 접근 가능
> [Fix] 게시글 수정 페이지 버그 처리

- web/src/containers/App/index.js
- web/src/containers/HomePage/index.js
1. Switch 컴포넌트를 이용하여 분기문을 더 확실히 구분
2. lazy Loading을 이용하여 라우터 기반 코드 스플릿팅 적용
> [Refact] 라우터 개선

- web/package-lock.json
- web/package.json
npm audit fix 명령어를 이용하여 취약성 개선
> [Fix] 패키지 취약성 개선

- web/src/containers/HomePage/Post/PostMiddle/PostImage.js
- web/src/containers/HomePage/Post/PostWrapper.js
- web/src/containers/Navigation/NavBackground.js
- web/src/containers/Navigation/Search/SearchWrapper.js
- web/src/containers/NewPostPage/Content.js
- web/src/containers/NewPostPage/CropContainer.js
- web/src/containers/NewPostPage/FileNameInput.js
- web/src/containers/NewPostPage/NewPostWrapper.js
- web/src/containers/NewPostPage/StyledSection.js
- web/src/containers/NewPostPage/index.js
- web/src/containers/NewPostPage/styles.js
- web/src/containers/PostDetailPage/PostDetailPageWrapper.js
- web/src/containers/PostDetailPage/PostSideBox/SideBoxWrapper.js
- web/src/containers/PostDetailPage/ViewPort.js
- web/src/containers/PostDetailPage/index.js
> [Refact] 반응형 페이지 적용

- api-server/api/graphql/index.js
- api-server/api/graphql/mutations/UserMutation.js
- api-server/api/graphql/mutations/index.js
- api-server/api/middlewares/auth.js
- api-server/api/services/UserService.js
- web/src/components/InputRow/StyledAside.js
- web/src/components/InputRow/index.js
- web/src/containers/EditProfilePage/UpdateProfile.js
- web/src/containers/EditProfilePage/Username.js
- web/src/containers/EditProfilePage/index.js
- web/src/containers/SettingPage/index.js
- web/src/queries/index.js
- web/src/queries/updateProfile.js
프로필 편집 페이지에서 사진을 업데이트 하는 기능 구현.
> [Feat] 프로필 사진 편집 기능 구현

- web/src/containers/AccountPage/lib/encryptor.js
- web/src/containers/EditProfilePage/index.js
- web/src/containers/NewPostPage/Content.js
- web/src/containers/NewPostPage/CropContainer.js
- web/src/containers/NewPostPage/index.js
- web/src/containers/PostDetailPage/PostSideBox/PostContent/PostText/Content/index.js
- web/src/containers/SettingPage/List/index.js
- web/src/containers/SettingPage/index.js
- web/src/containers/UserPage/UserPageInfo/UserInfo/Logout/index.js
선언되었지만 사용되지 않는 변수나 map으로 하위 컴포넌트를 생성할 때
key값을 정해주지않아서 생기는 react warning 제거.
> [Fix] 브라우저에 뜨는 react warning 제거

- web/src/containers/Navigation/Alarm/AlarmToolTip/index.js
- web/src/containers/Navigation/Alarm/AlarmToolTip/styles/AlarmNoResult.js
- web/src/containers/Navigation/Alarm/AlarmToolTip/styles/index.js
> [Fix] 알람 버그 수정

- web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmResult/index.js
알람 로그를 부를 때 null값이 매핑되어 에러가 나는 경우가 있어 수정.
> [Fix] 알람 로그 에러 수정

- web/config/nginx/conf.d/default.conf
> [Fix] nginx 세팅 변경

- README.md
README 파일을 수정하여 README가 프로젝트를 더욱 명확히 반영하도록 함.
> [Docs] README 파일 수정

- api-server/Dockerfile
- compose-prod.yml
- web/Dockerfile
- web/Dockerfile-dev
- web/config/nginx/conf.d/default.conf
- web/src/containers/AccountPage/lib/validator.js
- web/src/containers/App/index.js
- https 적용에 따른 Docker 설정파일 내용 수정.
> [Fix] Docker 설정파일 내용 수정

- api-server/db/migrations/20191217072900-create-client.js
- api-server/db/migrations/20191217072917-create-token.js
- OAuth 클라이언트를 등록할 때 필요한 Client 모델과 발급된 Token을 관리할 때 필요한 Token 모델 생성.
> [Feat] OAuth 서비스에 필요한 모델 생성

- api-server/api/graphql/index.js
- api-server/api/graphql/queries/FollowListQuery.js
- api-server/api/graphql/queries/FollowerListQuery.js
- api-server/api/graphql/queries/index.js
- api-server/api/graphql/types/UserType.js
- api-server/api/services/FollowListService.js
- web/src/components/UserListModal/ModalContent.js
- web/src/components/UserListModal/ModalHeader.js
- web/src/components/UserListModal/NoResult/NoResultWrapper.js
- web/src/components/UserListModal/NoResult/index.js
- web/src/components/UserListModal/UserListItem/index.js
- web/src/components/UserListModal/index.js
- web/src/components/UserListModal/styles.js
- web/src/containers/UserPage/UserPageInfo/UserInfo/CountIndicator/CountIndicatorWrapper.js
- web/src/containers/UserPage/UserPageInfo/UserInfo/CountIndicator/FollowIndicatorWrapper.js
- web/src/containers/UserPage/UserPageInfo/UserInfo/CountIndicator/index.js
- web/src/containers/UserPage/UserPageInfo/UserInfo/CountIndicator/styles.js
- web/src/containers/UserPage/UserPageInfo/UserInfo/index.js
유저 페이지에서 팔로우, 팔로워 클릭 시 해당하는 유저 리스트 출력하는 모달 구현
> [Feat] 유저 페이지에서 팔로우, 팔로워 클릭 시 해당하는 유저 리스트 출력하는 모달 구현

- api-server/db/migrations/20191217072900-create-client.js
- api-server/db/migrations/20191217072917-create-token.js
- Token 모델에 Client의 id 정보가 필요하여 컬럼 추가.
- Client 모델에 User의 id 정보가 필요하여 컬럼 추가.
> [Fix] Token, Client 모델에 컬럼 추가

- web/src/components/PostCardList/PostCardLine/index.js
- web/src/components/PostCardList/index.js
- 기존에 key값을 내려주지않아 발생하는 오류 해결.(키 값을 내려주도록 수정)
- for문을 사용하던 로직 reduce를 사용하도록 리팩토링
> [Refact] PostCardList 컴포넌트 리팩토링

- api-server/app.js
- api-server/config/redis-config.js
- api-server/package-lock.json
- api-server/package.json
- 서버가 재시작되더라도 session을 유지하기 위해 session 저장소로 Redis를 설정.
> [Feat] Session 저장소로 Redis 설정

- api-server/api/graphql/types/UserType.js
- web/src/components/FollowButton/index.js
- web/src/components/PostTop/MoreModal/index.js
- web/src/components/PostTop/MoreModal/styles/CustomFollowButton.js
- web/src/components/PostTop/MoreModal/styles/FollowCancelContent.js
- web/src/components/PostTop/MoreModal/styles/index.js
- web/src/containers/HomePage/index.js
- web/src/containers/NewPostPage/index.js
- web/src/containers/SettingPage/index.js
1. toast 일정시간 후 사라지게 설정
2. 모달창에서 팔로우 취소하능 기능 구현
> [Fix] 버그데이 버그 해결

- web/src/containers/HomePage/Post/index.js
- web/src/containers/HomePage/index.js
- web/src/containers/PostDetailPage/index.js
한 게시글에 일정 시간 이상 머물렀을 경우, 해당 게시글 상세 페이지에 대한
요청을 미리 보냄.
> [Refact] prefetch 전략 추가

- compose-dev.yml
- web/Dockerfile-dev
- web/config/nginx/conf.d/default-dev.conf
> [Fix] dev환경의 docker setting 수정

- api-server/api/middlewares/auth.js
- api-server/api/services/UserService.js
- web/src/containers/AccountPage/SignIn/index.js
- web/src/containers/AccountPage/SignIn/reducer.js
- web/src/containers/AccountPage/SignUp/index.js
- web/src/containers/AccountPage/SignUp/reducer.js
- web/src/containers/AccountPage/constants/index.js
- web/src/containers/AccountPage/lib/handlers.js
- web/src/containers/AccountPage/lib/validator.js
- 등록되지 않은 유저로 로그인하거나 잘못된 아이디나 비밀번호로 로그인을 시도할 시 에러 메시지 출력하도록
구현.
> [Fix] SignIn, SignUp 페이지 Error 핸들링 구현

- web/src/containers/PostDetailPage/PostSideBox/PostContent/CommentList/Comment/index.js
- web/src/containers/PostDetailPage/PostSideBox/PostContent/PostText/index.js
> [Fix] 상세 페이지 프로필 사진 적용

- api-server/api/graphql/types/UserType.js
graphql의 수정된 UserType이 다른 기능에 영향이 가서 다시 수정.
> [Fix] graphql UserType 수정

- web/src/containers/HomePage/Post/PostText/MainText/index.js
- web/src/containers/HomePage/Post/PostText/styles/TextMoreButton.js
- 본문 내용이 길었을 경우 더보기 버튼이 나오지 않았던 오류 수정.
> [Fix] 메인게시물의 본문 더보기 버튼 오류 수정

- api-server/config/sequelize-config.js
- production 환경에서 connection pool을 사용하도록 설정.
> [Fix] connection pool 설정 적용

- api-server/api/graphql/types/AlarmFromUserType.js
- api-server/api/graphql/types/LogType.js
- web/src/components/ToolTip/index.js
- web/src/components/ToolTip/styles/ToolTipArrow.js
- web/src/components/ToolTip/styles/ToolTipBackground.js
- web/src/components/ToolTip/styles/ToolTipBody.js
- web/src/containers/App/index.js
- web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmResult/index.js
- web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmResult/styles/AlarmActionWrapper.js
- web/src/containers/Navigation/Alarm/index.js
- web/src/containers/Navigation/Alarm/style/AlarmToolTipWrapper.js
- web/src/containers/Navigation/Alarm/style/index.js
- web/src/containers/Navigation/Search/styles/Input.js
- web/src/containers/Navigation/index.js
- web/src/queries/getLogs.js
알람 내에서 팔로우 가능하도록 수정.
툴팁과 아이콘과 모달간의 z-index 수정.
> [Fix] 알람 내에서 팔로우 기능 가능하도록 수정

- api-server/api/graphql/index.js
- api-server/api/graphql/queries/TaggedPostsQuery.js
- api-server/api/graphql/queries/index.js
- web/src/components/PostCardList/index.js
- web/src/containers/UserPage/ListSelector/SelectionTab/index.js
- web/src/containers/UserPage/ListSelector/SelectionTab/styles/BorderTopLink.js
- web/src/containers/UserPage/ListSelector/SelectionTab/styles/TabText.js
- web/src/containers/UserPage/ListSelector/index.js
- web/src/containers/UserPage/index.js
태그됨 탭을 선택시 해당 유저가 태그된 다른 유저의 게시물을 보여줌.
> [Feat] UserPage 태그됨 기능 구현

- oauth-server/routes/client.js
- oauth-server/services/client-service.js
- client를 등록하는 register메소드 수정.
> [Fix] client register 메소드 수정

- api-server/api/graphql/index.js
- api-server/api/graphql/queries/ClientQuery.js
- api-server/api/graphql/queries/index.js
- api-server/api/graphql/types/ClientType.js
- api-server/api/graphql/types/index.js
- api-server/api/models/Client.js
- web/src/containers/App/index.js
- web/src/containers/MyAppPage/MyAppList.js
- web/src/containers/MyAppPage/MyApplication.js
- web/src/containers/MyAppPage/index.js
- web/src/containers/MyAppPage/styles/ModalContent.js
- web/src/containers/MyAppPage/styles/ModalContentTitle.js
- web/src/containers/MyAppPage/styles/ModalRow.js
- web/src/containers/MyAppPage/styles/MyAppInfo.js
- web/src/containers/MyAppPage/styles/MyAppListWrapper.js
- web/src/containers/MyAppPage/styles/MyAppNoResult.js
- web/src/containers/MyAppPage/styles/index.js
- web/src/queries/getClient.js
- web/src/queries/index.js
유저가 OAuth 사용을 위해 등록한 앱 목록 페이지 구현.
> [Feat] 유저가 등록한 앱 목록 페이지 구현

- web/src/containers/AccountPage/lib/handlers.js
- web/src/utils/formUtils.js
- safari에서 로그인/회원가입 폼이 제대로 fetch되지 않는 버그 수정.
> [Fix] 로그인/회원가입 버그 수정

- web/src/containers/RegisterAppPage/index.js
클라이언트 등록할 때 url이 바뀌어서 수정.
클라이언트 테이블에 userId 컬럼이 추가되어서 수정.
> [Fix] 클라이언트 등록 버그 수정

- web/src/utils/formUtils.js
- 회원가입 폼 fetch시 회원정보를 제대로 보내지 못하는 버그 수정.
> [Fix] 회원가입 버그 수정

- web/src/components/FollowButton/index.js
추후 기능 구현을 위해 작성한 주석과 default props가 불필요해짐에따라 삭제.
> [Fix] FollowButton 주석, default props 삭제

- web/src/containers/PostDetailPage/PostSideBox/PostContent/CommentList/index.js
표시할 댓글이 더 없을 경우 (+) 버튼을 숨기고 fetch를 막음
> [Refact] 댓글이 더 없을 경우 버튼 제거

- web/src/components/LikeInfo/index.js
- web/src/containers/PostDetailPage/PostSideBox/PostContent/CommentList/index.js
- web/src/containers/PostDetailPage/index.js
- 아이디 링크 오류
- 상세 페이지 좋아요 글씨 버그
> [Fix] detail page bug

- web/src/containers/Navigation/index.js
> [Fix] 네비게이션 아이콘 CSS 수정

- web/src/components/PostTop/MoreModal/index.js
more modal에서 버튼 클랙시 아무 동작도 일어나지 않아
사용자 경험을 위해 창 닫히도록 수정.
> [Fix] more modal에서 버튼 클릭시 창 닫히도록 수정

- web/src/components/FollowButton/index.js
- web/src/containers/App/index.js
- web/src/containers/HashTagPage/index.js
- web/src/containers/UserPage/UserPageInfo/UserInfo/CountIndicator/index.js
- web/src/containers/UserPage/index.js
- web/src/queries/followList.js
- web/src/queries/followerList.js
- web/src/queries/hashTagPage.js
- web/src/queries/index.js
- web/src/queries/isLoggedIn.js
- web/src/queries/requestFollowing.js
- web/src/queries/requestFollowingCancellation.js
- web/src/queries/taggedPosts.js
- web/src/queries/userPage.js
쿼리문이 분리되지않은 컴포넌트와 컨테이너의 쿼리문 분리.
> [Refact] 쿼리문 분리

- web/src/components/LikeInfo/index.js
- web/src/components/UserListModal/UserListItem/index.js
- web/src/components/UserListModal/index.js
- web/src/containers/HomePage/Post/PostMiddle/index.js
- web/src/containers/PostDetailPage/PostSideBox/UtilityBlock/index.js
- web/src/containers/UserPage/UserPageInfo/UserInfo/CountIndicator/index.js
- 팔로워 모달 구조 변경
- 메인 페이지 및 상세 페이지에 팔로워 모달 적용
> [Refact] 팔로워 모달 리팩토링

- api-server/api/graphql/queries/TaggedPostsQuery.js
- web/src/queries/taggedPosts.js
myId의 타입이 GraphQLID로 바뀜에 따라 수정.
> [Refact] TaggedPosts 쿼리 myId변수 타입 수정

- api-server/api/services/user-service.js
- web/src/containers/EditProfilePage/index.js
프로필을 편집할 때 insert시 컬럼명 오입력으로 생긴 오류 수정.
편집이 완료된 후 바로 페이지들에 반영이되지 않아 반영되도록 수정.
> [Fix] 프로필 편집 페이지 오류 수정

- api-server/api/graphql/queries/FollowListQuery.js
- api-server/api/graphql/queries/FollowerListQuery.js
- api-server/api/graphql/queries/FollowingPostListQuery.js
- api-server/api/graphql/types/UserType.js
- api-server/api/services/followlist-service.js
- api-server/api/services/post-service.js
- web/.eslintrc.js
- web/package-lock.json
- web/package.json
- web/src/components/UserListModal/ModalContent.js
- web/src/components/UserListModal/UserListItem/UserListItemWrapper.js
- web/src/components/UserListModal/UserListItem/index.js
- web/src/components/UserListModal/index.js
- web/src/components/UserListModal/selectUpdateQuery/follow.js
- web/src/components/UserListModal/selectUpdateQuery/follower.js
- web/src/components/UserListModal/selectUpdateQuery/index.js
- web/src/queries/followList.js
- web/src/queries/followerList.js
> [Refact] 팔로워 리스트에 무한스크롤 추가

- oauth-server/grant-types/authorization-code.js
- oauth-server/grant-types/implicit.js
- oauth-server/routes/oauth.js
- Grant type 중 Implicit 방식 구현.
> [Feat] Implicit grant type 구현

- oauth-server/grant-types/authorization-code.js
- oauth-server/middlewares/request-validator.js
- oauth-server/routes/oauth.js
- oauth-server/services/token-service.js
- request의 grant_type이 refresh_token일 경우, access token을 재발급 해주는 기능 구현.
> [Feat] refresh token에 대한 처리 구현

- api-server/config/sequelize-config.js
- dev환경에서도 sequelize에 connection pool 설정을 추가.
> [Fix] dev환경에서의 sequelize 설정 변경

- web/src/components/UserListModal/index.js
팔로워를 클릭하고 로딩이 될 때 끄면 에러가 나는 버그 수정
> [Fix] 팔로우 목록 버그 수정

- api-server/api/graphql/mutations/PostMutation.js
- api-server/api/graphql/queries/FollowListQuery.js
- api-server/api/graphql/queries/FollowerListQuery.js
- api-server/api/graphql/queries/FollowingPostListQuery.js
updatedAt의 default가 서버 실행 시간이던 것을 삭제
delete 관련 버그 해결
> [Fix] 서버 버그 수정

- web/src/components/LikeInfo/index.js
- web/src/containers/PostDetailPage/PostSideBox/PostContent/PostText/Content/styles/ContentWrapper.js
- web/src/containers/PostDetailPage/PostSideBox/PostContent/PostText/styles/PostTextWrapper.js
- 게시글과 댓글 사이의 경계 생성
- 좋아요 클릭 수 프로필 사진 오류 해결
> [Fix] UI 버그 수정

- web/src/components/UserListModal/index.js
> [Fix] 팔로우 버튼 버그 수정

- web/src/containers/HomePage/Post/PostMiddle/index.js
- web/src/containers/PostDetailPage/PostSideBox/IconGroup/index.js
좋아요를 연타하였을 때 좋아요가 반대로 반영되는 버그 해결.
> 좋아요 아이콘 버그 해결

- web/src/components/UserListModal/index.js
유저리스트 모달에서 팔로우 취소 체크 모달을 띄울 때 유저리스트의
인피니트스크롤 모듈에 적용된 will change속성에 체크 모달에 영향을
줘서 UI가 예상대로 나오지 않아 will change 속성 변경.
> [Fix] 유저리스트 CSS 변경

- api-server/api/graphql/index.js
- api-server/api/graphql/queries/RandomListQuery.js
- api-server/api/graphql/queries/index.js
- api-server/api/services/randomlist-service.js
- api-server/error/index.js
- web/src/containers/HomePage/NoFollowing/index.js
- web/src/containers/HomePage/NoFollowing/styles/NoFollowingWrapper.js
- web/src/containers/HomePage/NoFollowing/styles/StyledModalContent.js
- web/src/containers/HomePage/NoFollowing/styles/StyledModalWrapper.js
- web/src/containers/HomePage/NoFollowing/styles/index.js
- web/src/containers/HomePage/index.js
- web/src/queries/randomList.js
- 팔로우가 없는 경우 유저를 랜덤으로 추천하여 좋은 사용자 경험을 제공함.
> [Fix] 팔로우가 없는 경우 랜덤 추천 팔로우 구현

- api-server/api/graphql/index.js
- api-server/api/graphql/queries/LikerInfoListQuery.js
- api-server/api/graphql/queries/index.js
- api-server/api/services/likerinfolist-service.js
- api-server/error/index.js
- web/src/components/LikeInfo/index.js
- web/src/components/UserListModal/index.js
- web/src/components/UserListModal/selectUpdateQuery/index.js
- web/src/components/UserListModal/selectUpdateQuery/liker.js
- web/src/queries/index.js
- web/src/queries/likerInfoList.js
좋아요 인원 수를 클릭하였을 때, 좋아요를 클릭한 사람들의 리스트가 모달에 나옴.
> [Feat] 좋아요 리스트 모달 구현

- api-server/utils/upload.js
- web/src/containers/AccountPage/SignIn/index.js
- web/src/containers/AccountPage/SignUp/index.js
- 이미지 업로드 시 이미지가 제대로 업로드되지 않는 경우에 대한 에러 핸들링.
> [Fix] 이미지 업로드 에러 핸들링

- web/src/containers/AccountPage/SignUp/index.js
- web/src/containers/AccountPage/constants/index.js
- web/src/containers/AccountPage/lib/validator.js
- web/src/containers/App/index.js
- web/src/containers/EditProfilePage/index.js
- 회원 가입 페이지에 비밀번호 확인 기능 추가
- 프로필 편집 페이지에 유효성 확인 추가
- 비밀번호 변경 페이지 제거
> [Fix] validation 개선

- web/src/components/Loading/styles/Backdrop.js
> [Fix] 위치 설정

- oauth-server/routes/client.js
- client 등록 HTTP method를 POST로 변경
> [Fix] client 등록 HTTP method 변경

- oauth-server/models/client.js
client model에 UserId가 누락되어 이를 추가.
> [Fix] client model 수정

- web/src/containers/App/index.js
- web/src/containers/UserPage/index.js
기존에는 props형태로 myInfo를 전달했지만 쿠키를 도입함으로써
props가 아닌 쿠키로 myInfo정보를 받도록 수정.
> [Refact] UserPage에서 쿠키로 myInfo 받도록 수정

- web/src/components/ToolTip/styles/ToolTipBody.js
- web/src/containers/NewPostPage/index.js
새게시물 등록에 대해 대용량 이미지 또는 이모지 입력에 대한 에러핸들링.
> [Fix] 새게시물에 대한 에러 핸들링

- web/src/components/FollowButton/index.js
- web/src/containers/AccountPage/SignUp/reducer.js
- web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmResult/index.js
- 회원가입 비밀번호 확인 버그 수정
- 알람 툴팁 버그 수정
- 팔로우 버튼 loading 추가
> [Hotfix] 일부 버그 수정

- oauth-server/app.js
- oauth-server/grant-types/authorization-code.js
- oauth-server/grant-types/implicit.js
- oauth-server/middlewares/request-validator.js
- oauth-server/routes/oauth.js
- oauth-server/services/token-service.js
- Authroization Code, AccessToken 발급에 대한 에러 핸들링 추가.
> [Feat] Error Handling 추가 및 수정

- oauth-server/middlewares/request-validator.js
- Access Token이 만료되었는 지 여부를 판단하는 로직을 추가하여 만료된 Access Token으로 API 요청을 하지 못하도록 함.
> [Fix] Access Token 만료 여부를 판단하는 로직추가

- oauth-server/grant-types/authorization-code.js
- oauth-server/public/css/signin.css
- oauth-server/views/signin.html
- Authorization code 방식에서 access token을 발급하는 메소드의 버그 수정
> [Fix] Authorization code의 token handler 버그 수정

- oauth-server/services/user-service.js
- 유저 프로필을 요청하는 API에 대한 응답으로 id, email, profile Image를 받을 수 있도록 수정.
> [Fix] 유저 프로필 API 수정
