web/src/components/LikeIcon/LikeIconSpan.js
web/src/components/LikeIcon/StyledSpan.js
web/src/components/LikeIcon/Wrapper.js
web/src/components/LikeIcon/index.js

- icon 이미지 파일이 변경됨 따라 background-position 변경.
- Wrapper 컴포넌트는 불필요하게 div를 하나 더 생성하므로 제거.
- StyledSpan과 SpanStyles파일을 분리하는 것이  불필요하다고
판단하여 LikeIconSpan 파일로 통합.
- LikeIconSpan으로 통합됨에 따라 index.js 코드 수정.

[Fix] 불필요한 파일 통합 및 icon이미지 파일 변경에 따른 수정

---

web/src/components/LikeIcon/LikeIconSpan.js
web/src/components/LikeIcon/index.js

ratio 값에 따라서 좋아요의 하트 이미지가 짤리는 현상을
고치기 위해 background image의 size와 position 값을 계산하는
방식과 이미지 span의 width, height 값을 계산하는 방식을 수정.

[Fix] 비율에 따른 좋아요 이미지가 짤리는 버그 수정

---

api-server/api/models/post.js

post model에 새로 추가된 column의 datatype이 잘못 설정되어
api-server가 실행되지 않아 수정.

[Fix] sequelize post model 수정

---

web/src/components/PostCardList/PostCardLine/PostCard/MarginalPostCard.js

PostCardLine에서 마지막 카드만 margin-left가 적용되고 나머지는
적용이 안되던 것을 마지막 카드만 적용이 안되고 나머지 카드는
적용되도록 변경.

[Fix] PostCardList margin-left 버그 수정

---

api-server/api/graphql/queries/SearchHashtagQuery.js
api-server/api/graphql/queries/SearchUserQuery.js
web/src/components/ToolTip/ToolTipArrow.js
web/src/components/ToolTip/ToolTipBackground.js
web/src/components/ToolTip/ToolTipBody.js
web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmNoResult.js
web/src/containers/Navigation/Search/Input.js
web/src/containers/Navigation/Search/SearchToolTip/SearchNoResult.js
web/src/containers/Navigation/Search/SearchToolTip/SearchResult/ResultInfo.js
web/src/containers/Navigation/Search/SearchToolTip/SearchResult/SearchResultWrapper.js
web/src/containers/Navigation/Search/SearchToolTip/SearchResult/index.js
web/src/containers/Navigation/Search/SearchToolTip/SearchToolTipWrapper.js
web/src/containers/Navigation/Search/SearchToolTip/index.js
web/src/containers/Navigation/Search/SearchToolTip/styles.js
web/src/containers/Navigation/Search/index.js
web/src/query/navigationQuery.js

1. 검색결과가 없을시 검색 결과가 없다는 응답 툴팁에 보여주도록 수정.
2. fetch를 새로운 useFetch 사용하도록 리팩토링.
3. SearchResult component의 result를 state관리 형태로 변경.
4. 랜덤 정렬 부분 목적을 명확히 표시하기 위해 함수화.
5. 3개 이상의  state를 reducer로 관리하도록 리팩토링.
6. css관련 색상 palette에 있는 색상으로 변경.
7. 검색 결과 데이터 최대 20 응답하도록 수정.
8. 최초 마운트시 useEffect 실행되지 않도록 수정.

[Refact] 검색 기능 리팩토링

---

web/src/containers/UserPage/index.js

사용자 페이지간 이동 시 PostCardList가 최신화되지 않는 버그 발생.
useEffect함수의 deps에 postCardURL을 추가하여 url변경 시(즉, 다른
유저 페이지로 이동 시) PostCardList가 최신화 되도록 변경.
Close #200

[Fix] 사용자 페이지간 이동 시 PostCardList 최신화

---

web/src/containers/NewPostPage/index.js

새게시물의 사진을 crop할 때 파라미터를 잘못 입력하여 확대되어
crop되고 저장되는 부분 파라미터 수정으로 오류 수정.

[Fix] 새게시물 사진 crop 확대되어 되는 부분 수정

---

web/src/containers/NewPostPage/index.js

새게시물 작성시 사진 정보가 없으면 제출이 되지않아
경고창을 띄우도록 수정.

[Fix] 새게시물 작성시 사진 정보가 없으면 경고창 띄우도록 수정

---

web/src/containers/Navigation/index.js

네비게이션 프로필 아이콘이 무조건 default로 나오게 되어있어
로그인한 유저 사진으로 교체
closed #96

[Fix] 네비게이션 프로필 아이콘에 로그인한 유저 사진으로 교체

---

api-server/api/graphql/queries/SearchQuery.js

서버에서의 테이블명과 달라서 서버에서 검색 기능이 작동하지 않는
오류가 발생했기 때문에 테이블명 수정.
closed #242 and closed #249

[Fix] 검색기능 버그 수정

---

web/src/components/LikeIcon/index.js
web/src/components/LikeInfo/Context/LikerInfoContext.js
web/src/containers/HomePage/Post/PostMiddle/index.js

- 자신이 올린 게시물에 좋아요가 하나도 없는 상황에서 자신이 좋아요를 눌렀을 때, 좋아요 문구에 프로필 사진이 보이는 버그가 있어서 이를 수정하여 프로필 사진이 뜨지 않도록 함.
close #273

[Fix] 좋아요 문구 버그 수정

---

api-server/api/graphql/queries/hashTagPageQuery.js
api-server/api/services/HashTagPageService.js
web/src/components/AnnouncementMessage/AnnouncementMessageWrapper.js
web/src/components/AnnouncementMessage/index.js
web/src/containers/HashTagPage/index.js

- 해쉬태그 페이지 요청에 대한 api-server의 처리 로직을 파일로 분리하여 정리함.
- 해쉬태그가 게시물을 하나도 가지고 있지 않는 경우에 대한 예외처리.
- 공지문구에 css를 적용해주는 AnnouncementMessage 구현
- 로딩시 스피너가 등장하도록 함.
Close #296

해쉬태그 페이지 리팩토링 및 AnnouncementMessage 구현

---

web/src/containers/HashTagPage/index.js
web/src/containers/UserPage/index.js

이전 커스텀 훅 useFetch를 사용하면서 url변경에 따라 새로운 게시물을
갱신하기위해 useEffect를 활용했던 부분이 useQuery를 사용하게됨에
따라 불필요하여 삭제함.

[Refact] UserPage, HashTagPage의 불필요한 useEffect 제거

---

web/src/components/Button/index.js
web/src/containers/UserPage/UserPageInfo/UserInfo/StyledFollowButton.js
web/src/containers/UserPage/UserPageInfo/UserInfo/UserNameLabel/UserNameLabelWrapper.js
web/src/containers/UserPage/UserPageInfo/UserInfo/index.js
web/src/containers/UserPage/UserPageInfo/index.js
web/src/containers/UserPage/index.js

- 기존에 Button컴포넌트에 border에대한 디자인이 반영되지않아 border 디자인 반영.
- 기존의 UserPage는 본인페이지를 구별하지 못하여 본인페이지임에도 불구하고 FollowButton을 표시했다. 하지만 myInfo의 username과 UserPage의 username을 비교하여 본인페이지인지를 확인하고 본인페이지일 경우 팔로우버튼대신  개인정보설정버튼을 렌더링하도록 변경하였다. 개인정보설정버튼은 개인정보설정화면으로 보내준다.
Close #298

Button컴포넌트 디자인 수정 및 UserPage 마이페이지 기능 추가

---

api-server/api/graphql/queries/SearchQuery.js

로컬에서는 테이블명에 대소문자 구분이 없지만 배포서버에는 있어
테이블명 오류로 검색이 되지않아 테이블명 수정.
closed #356 and closed #342

[Fix] 서버에서 검색 안되는 버그 수정

---

api-server/api/graphql/mutations/RequestFollowing.js
api-server/api/graphql/mutations/RequestFollowingCancellation.js
api-server/api/graphql/queries/UserPageQuery.js
api-server/api/graphql/types/UserInfoType.js
api-server/api/services/RequestFollowingCancellationService.js
api-server/api/services/RequestFollowingService.js
api-server/api/services/UserPageService.js
web/src/components/FollowButton/index.js
web/src/containers/UserPage/UserPageInfo/UserInfo/index.js
web/src/containers/UserPage/UserPageInfo/index.js
web/src/containers/UserPage/index.js

- 팔로우버튼의 팔로우 기능이 정확하게 동작하도록 요청 변경, UserPage에서 팔로우 취소 및 팔로우 시 즉각적으로 반영되도록 변경
- 팔로우를 할 때는 로그 테이블에 등록되어 상대방에게 알람이 가야하고 팔로우를 취소할 떄는 로그테이블에서 삭제되어 알람이 가지 않아야한다. 팔로우 또는 팔로우 취소시 로그테이블에 로우를 추가 및 삭제하여 해당 기능을 구현.

[팔로우버튼, 유저페이지] 팔로우버튼 정상작동 구현, UserPage 팔로우 데이터 즉각 반영 구현

---

web/src/containers/UserPage/ListSelector/SelectionTab/BorderTopLink.js
web/src/containers/UserPage/ListSelector/SelectionTab/TabText.js
web/src/containers/UserPage/ListSelector/SelectionTab/index.js
web/src/containers/UserPage/ListSelector/index.js

ListSelector에서 선택되었는지를 알려주는 변수 및 props인 isselected가 카멜케이스가 적용되지않아 isSelected로 수정함.

[유저페이지] 카멜케이스가 적용되지 않은 변수명 변경

---

web/src/components/PostCardList/PostCardLine/PostCard/MarginalPostCard.js

게시된 이미지에 배경색이 없는 경우 post card의 영역이 명확하게
구분되지 않는다는 의견이 있어 기본적으로 흰색 배경을 부여함.

[Fix] post card에 배경색 추가

---

api-server/api/services/HashTagPageService.js
api-server/api/services/UserPageService.js

유저페이지와 해쉬태그페이지에서 오래된 게시물부터 보이는 버그가
있었음. updatedAt을 DESC로 order by하여 최신글이 위로 올라오도록
수정함.

[Fix] 게시물이 최신글부터 리스트되도록 수정

---

web/src/containers/HashTagPage/index.js

리뷰어님의 의견에따라 반복적으로 호출되는 하위객체를
destructuring을 활용하여 상위객체를 부르지않고 사용.

[Refact] destructuring으로 중복되는 코드 제거

---

web/src/containers/HomePage/Post/PostText/MainText/lib/index.js

- '#'을 제외한 hashtag의 최대길이가 44글자이므로 파싱이 44글자이상 되지 않도록 수정.

[Fix] hashtag가 최대 44글자까지 파싱되도록 수정

---

api-server/api/middlewares/auth.js

쿠키를 발급할 때에 id 값을 int로 발급하여 === 이 일치하지 않는 버그
해결.

[Fix] 게시글 수정 페이지에 접근이 안되는 버그 수정

---

api-server/api/graphql/mutations/UserMutation.js

graphql 파일들 리팩토링 과정에서 int를 ID로 바꾸지 않은 파일이 있어
생긴 오류 수정.

[Fix] graphql type때문에 생긴 오류 수정

---

web/src/components/UserListModal/UserListItem/index.js

기존의 UserListModal에서는 본인 계정에도 FollowButton을 렌더링했음.
하지만 본인계정을 팔로우하는 기능은 제공하지 않기 때문에 렌더링하지
않도록 수정.

[Refact] UserListModal에서 본인 계정의 FollowButton 렌더링 방지

---

api-server/api/graphql/types/UserType.js
web/src/components/PostTop/MoreModal/index.js
web/src/queries/followingPostList.js
web/src/queries/readPost.js

메인페이지와 디테일 페이지 모두 post type을 반환하는데 구조상 팔로우
여부를 반환하는 것이 성능 저하를 일으켜 팔로우 취소 버튼 체거.

[Fix] more modal에서 팔로우 취소 버튼 제거

---

api-server/api/graphql/mutations/PostMutation.js
api-server/api/services/PostService.js

게시물 수정시 새로운 해시태그일 경우에 해시태그 테이블에 insert되지
않아서 게시물이 검색이 안되는 경우가 생겨 테이블에 insert하도록 수정.
새로운 유저태그일 경우에 유저태그 테이블에 insert되지 않아서 
게시물이 검색이 안되는 경우가 생겨 테이블에 insert하도록 수정.

[Fix] 게시물 수정시 새로운 해시태그 및 유저태그 반영되도록 수정

---

api-server/api/graphql/queries/FollowListQuery.js
api-server/api/graphql/queries/FollowerListQuery.js
api-server/api/services/followlist-service.js

기존이 쿼리는 시퀄라이즈가 여러번 데이터베이스에 요청을 보내
커넥션을 생성하고 제거하는데 코스트가 컸다. 그러한 코스트를 줄이기
위해 하나의 쿼리로 원하는 결과값을 얻도록 수정.

[Refact] 팔로우, 팔로워 조회시 쿼리 최적화

---

web/src/components/FollowButton/index.js
web/src/components/FollowCheckingModal/index.js
web/src/components/UserListModal/UserListItem/index.js
web/src/containers/Navigation/Alarm/AlarmToolTip/AlarmResult/index.js
web/src/containers/UserPage/UserPageInfo/UserInfo/index.js
web/src/containers/UserPage/UserPageInfo/index.js

팔로우 취소를 확인하는 모달에 상대방의 프로필 사진이 뜨지않아
상대방의 프로필 사진이 뜨도록 props를 내려주게 수정.

[Fix] 팔로우 취소때 상대방의 프로필 사진이 뜨도록 수정

---

web/src/containers/Navigation/Search/SearchToolTip/index.js
web/src/containers/Navigation/Search/index.js

검색할 때 한글자를 검색했다가 지우고 다시 쓰는 경우 툴팁의 활성화
결정 과정이 매끄럽지 않아 깜빡이는 현상 발생해 사용자 경험을 위해
fetch가 실행된 후에 tooltip의 활성화를 결정하도록 수정.

[Fix] 검색 기능 버그 수정

---

web/src/containers/NewPostPage/index.js

새게시물 등록시 5MB가 넘는 파일은 전송하지 않도록 수정.

[Fix] 새게시물 너무 큰 이미지는 전송하지 않도록  수정

---

web/src/containers/App/index.js

비밀번호 변경페이지 컴포넌트를 담고있는 changePasswordPage 변수는
현재 사용되지 않기 때문에 삭제.

[Fix] 사용하지 않는 페이지라 사용되지 않는 코드 삭제
